# Generated by Django 5.2.8 on 2025-11-13 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('grado_aplicar', models.CharField(max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(default='Pendiente', max_length=15)),
                ('acudiente_aspirante', models.OneToOneField(db_column='id_acudiente_aspirante', on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='usuarios.acudiente_aspirante')),
                ('infante_aspirante', models.OneToOneField(db_column='id_infante_aspirante', on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='usuarios.infante_aspirante')),
            ],
            options={
                'db_table': 'Solicitud',
            },
        ),
    ]
