# Generated by Django 5.2.8 on 2025-12-09 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('usuarios', '0002_estudiante_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='acudiente_aspirante',
            field=models.ForeignKey(db_column='id_acudiente_aspirante', on_delete=django.db.models.deletion.CASCADE, to='usuarios.acudiente_aspirante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='infante_aspirante',
            field=models.ForeignKey(db_column='id_infante_aspirante', on_delete=django.db.models.deletion.CASCADE, to='usuarios.infante_aspirante'),
        ),
    ]
