# Generated by Django 5.2.8 on 2025-11-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_logros',
            fields=[
                ('id_categoria_logros', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('descripcion_categoria', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Categoria_logros',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=15)),
                ('cupos_grado', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'Grado',
            },
        ),
        migrations.CreateModel(
            name='Periodo_academico',
            fields=[
                ('anio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'Periodo_academico',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=25)),
                ('cupos_grupo', models.DecimalField(decimal_places=0, default=10, max_digits=2)),
                ('grado', models.ForeignKey(db_column='id_grado', null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
                ('profesor_director', models.ForeignKey(blank=True, db_column='id_persona_profesor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profesor')),
            ],
            options={
                'db_table': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id_logro', models.AutoField(primary_key=True, serialize=False)),
                ('concepto_logro', models.CharField(max_length=50)),
                ('descripcion_logro', models.CharField(max_length=250)),
                ('categoria_logros', models.ForeignKey(db_column='id_categoria_logros', on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='academico.categoria_logros')),
                ('grado', models.ForeignKey(blank=True, db_column='id_grado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros', to='academico.grado')),
            ],
            options={
                'db_table': 'Logro',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion_corte1', models.CharField(max_length=15)),
                ('evaluacion_corte2', models.CharField(max_length=15)),
                ('evaluacion_corte3', models.CharField(max_length=15)),
                ('logro', models.ForeignKey(db_column='id_logro', on_delete=django.db.models.deletion.CASCADE, to='academico.logro')),
            ],
            options={
                'db_table': 'Evaluacion',
            },
        ),
        migrations.AddField(
            model_name='grado',
            name='periodo_acadmico',
            field=models.ForeignKey(db_column='anio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.periodo_academico'),
        ),
    ]
