# Generated by Django 5.2.8 on 2025-11-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('boletines', '0002_alter_boletin_nombre_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='boletin',
            field=models.ForeignKey(blank=True, db_column='id_boletin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='boletines.boletin'),
        ),
    ]
