# Generated by Django 5.2.8 on 2025-11-16 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('NIT', models.DecimalField(decimal_places=0, max_digits=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'Persona',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
            ],
            options={
                'db_table': 'Acudiente',
            },
        ),
        migrations.CreateModel(
            name='Acudiente_aspirante',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('correo_electronico_aspirante', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Acudiente_aspirante',
            },
        ),
        migrations.CreateModel(
            name='Administrador_academico',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
            ],
            options={
                'db_table': 'Administrador_academico',
            },
        ),
        migrations.CreateModel(
            name='Administrador_de_Usuarios',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
            ],
            options={
                'db_table': 'Administrador_de_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Infante_aspirante',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'Infante_aspirante',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
            ],
            options={
                'db_table': 'Profesor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('acudiente', 'Acudiente'), ('profesor', 'Profesor'), ('administrador_academico', 'Administrador Académico'), ('administrador_usuarios', 'Administrador de Usuarios')], max_length=30)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.persona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('fecha_nacimiento', models.DateField()),
                ('acudiente', models.ForeignKey(db_column='id_persona_acudiente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='usuarios.acudiente')),
            ],
            options={
                'db_table': 'Estudiante',
            },
        ),
    ]
