# Generated by Django 5.2.8 on 2025-11-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_evaluacion_boletin'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(db_column='id_grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='academico.grupo'),
        ),
    ]
