# Generated by Django 5.2.8 on 2025-11-19 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_estudiante_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id_citacion', models.AutoField(db_column='id_citacion', primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField(db_column='fecha_cita')),
                ('lugar_cita', models.CharField(db_column='lugar_cita', max_length=50)),
                ('hora_cita', models.TimeField(db_column='hora_cita')),
                ('tipo_cita', models.CharField(db_column='tipo_cita', max_length=15)),
                ('acudiente', models.ForeignKey(db_column='id_persona_acudiente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.acudiente')),
                ('administrador', models.ForeignKey(db_column='id_persona_administrador_academico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.administrador_academico')),
            ],
            options={
                'db_table': 'Citacion',
            },
        ),
    ]
