# Generated by Django 5.2.8 on 2025-11-19 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id_boletin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=30)),
                ('profesor_director', models.CharField(max_length=250)),
                ('estudiante', models.ForeignKey(db_column='id_persona_estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines', to='usuarios.estudiante')),
                ('periodo_academico', models.ForeignKey(db_column='anio', on_delete=django.db.models.deletion.CASCADE, to='academico.periodo_academico')),
            ],
            options={
                'db_table': 'Boletin',
            },
        ),
    ]
