# Generated by Django 5.2.8 on 2025-11-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='nombre_grupo',
            field=models.CharField(max_length=30),
        ),
    ]
