# Generated by Django 5.2.8 on 2025-12-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_estudiante_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoRestablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_datos', models.IntegerField(default=0)),
                ('intentos_contrasena', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('token_validacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_token', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intento_restablecimiento', to='usuarios.usuario')),
            ],
        ),
    ]
